@startuml name qweb happypath
title SF-Backend Interactions (Charlie Squad)

skinparam roundCorner 10
hide footbox

actor user as "User"

box "Salesforce"
    database object as "CustomObject__c"
    participant code as "Code"
end box

box "Backend"
   boundary endpoint as "Endpoint"
   participant lib as "Code"
end box


== Feature 1 ==
user --> object : create
object --> code : trigger

== Feature 2 ==

@enduml